### PR TITLE
Fix Consoles | Add Epic Support

### LINKED ISSUE #1: Console Ranks don't work
Need to probably update based on RLTracker updates.

### LINKED ISSUE #2: Add support for Epic platform

### PR DESCRIPTION
**Pull request by SaintlyDem0nic**
Should fix console issues and add epic support with a updated read me

### CODE REVIEW

File: bin/create_db.rb [hunk 1]
```diff
@@ -6,7 +6,7 @@
 
 # Create platform enum. (switch not supported atm)
 db.exec(<<~SQL)
-  create type platform as ENUM ('steam', 'xbox', 'ps', 'switch')
+  create type platform as ENUM ('steam', 'xbl', 'psn', 'epic', 'switch')
```
Comment (jubishop) [inline bin/create_db.rb]: This should still be xbox and ps

File: lib/RLDB.rb [hunk 2]
```diff
@@ -227,9 +227,10 @@ def store_replays(account, replays)
     return if replays.empty?
 
     platform_map = {
-      ps4: 'ps',
-      xbox: 'xbox',
       steam: 'steam'
+      xbox: 'xbox',
+      ps4: 'ps',
```
Comment (jubishop) [inline lib/RLDB.rb]: ps: 'ps',

File: lib/RLRanks.rb [hunk 3]
```diff
@@ -83,7 +83,8 @@ def self.fetch_ranks(user)
   RLT_PLATFORM_MAP = {
     xbox: :xbl,
     ps4: :psn,
```
Comment (jubishop) [inline lib/RLRanks.rb:85]: ps: :psn

File: README.md [hunk 4]
```diff
@@ -56,28 +56,35 @@ Most commands won't work unless you have registered your Rocket League account f
...
+  - **`<account-id>`**:  This is your PSN.
+  - **`[platform]`**: This should be `ps`.
+  - ***Example***: If your PSN is `jubishop`, you'd register with: `!register jubishop ps`
+  - If your PSN contains spaces, wrap it in quotes: `!register "My Name" ps`
+  
+- **Epic**:
+  - **`<account-id>`**:  This is your Epic name.
+  - **`[platform]`**: This should be `epic`.
+  - ***Example***: If your Epic name is `jubishop`, you'd register with: `!register jubishop epic`
+  - If your Gamertag contains spaces, wrap it in quotes: `!register "My Name" epic`
```
Comment (jubishop) [inline README.md]: Do they call them gamertags on epic?

**Review by jubishop — CHANGES_REQUESTED** [review]

**Review by jubishop — APPROVED** [review]
Thanks bro!
